### ISSUE TITLE
app.py author正则匹配有问题

### ISSUE THREAD

**Issue by tuola** [grt1st/wooyun_search#3]
wooyun-2013-022100.html

漏洞作者：		`漏洞作者：		<a href="http://www.wooyun.org/whitehats/z@cx"><span class="__cf_email__" data-cfemail="a8d2e8cbd0">[email&#160;protected]</span><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></a>`

原来的正则：`pattern3=re.compile(r'>(.*)</a>')`
修正后的正则：`pattern3=re.compile(r'<a` href="http://www.wooyun.org/whitehats/(.*?)">')

**Comment by tuola** [comment]
pattern3=re.compile(r'<a href="http://www.wooyun.org/whitehats/(.*?)">')

**Comment by tuola** [comment]
`pattern3=re.compile(r'<a href="http://www.wooyun.org/whitehats/(.*?)">')`

**Comment by grt1st** [comment]
thx，原来问题在这里
