### ISSUE TITLE
知识库页面显示有问题

### ISSUE THREAD

**Issue by fongzii** [grt1st/wooyun_search#5]
知识库所有网页左边显示黑条，文章不居中，被左边的黑条挡住了，基本不能愉快的看
html的css、js、image原来的位置是static/drops/下的css、js、full三个文件夹，楼主自己在html中嵌入的css有问题，我调了一下，不过能力有限调不出来
我把原来的代码复制在html中显示正常，不过这样做好麻烦，那么多网页没法一张纸修改，请高手出招

**Comment by fongzii** [comment]
解决了😄
在wooyun_search文件夹下创建文件夹static/drops/，然后把drops下面的css、js、full文件夹移动到static/drops/里面
建议建个static文件，把bugs、drops文件统一放在里面，并修改建立索引脚本里的文件路径为static/drops、static/bugs。就不会出现这个问题了
我看楼主把bugs、drops网页的代码都做了修改，很想知道这么多不同的页面你怎么改的，不会一张张改的吧😅光粘贴复制都要好久😀

**Comment by grt1st** [comment]
肯定是用脚本改啊。解决了就好，恭喜

**Comment by fongzii** [comment]
脚本好强大，可是我不会☹

**Comment by fongzii** [comment]
大神，可不可以把批量修改网页的脚本给我学习一下😙
