### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by whoadmin** [grt1st/wooyun_search#8]
http://...../wooyun/search.php?kind=bugs&keywords=a&page={(1+1)}
类似这样的就不能下一页了

**Comment by grt1st** [comment]
修改search.php即可。

用编辑器打开代码，搜索`search.php`，在所有的`seaarch.php`前面添加`http://...../wooyun/`即可。

**Comment by whoadmin** [comment]
感谢, 这一段已经用全局函数做了一个路径识别
